server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///ErpSysteam?useSSL=true&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: HTML5
logging:
  level:
    com.fzy.erpsystem.dao: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰转换
